import type { Metadata } from "next";
import { BootcampHero } from "@/components/bootcamp/BootcampHero";
import { ProblemTimeline } from "@/components/bootcamp/ProblemTimeline";
import { LearningGapsRoadmap } from "@/components/bootcamp/LearningGapsRoadmap";
import { HiddenGapsSigns } from "@/components/bootcamp/HiddenGapsSigns";
import { WhySummerSection } from "@/components/bootcamp/WhySummerSection";
import { AssessmentShowcase } from "@/components/bootcamp/AssessmentShowcase";
import { HowItWorksRoadmap } from "@/components/bootcamp/HowItWorksRoadmap";
import { BootcampFeatures } from "@/components/bootcamp/BootcampFeatures";
import { CurriculumTimeline } from "@/components/bootcamp/CurriculumTimeline";
import { TeachingPhilosophy } from "@/components/bootcamp/TeachingPhilosophy";
import { BeforeAfterSection } from "@/components/bootcamp/BeforeAfterSection";
import { EducatorSection } from "@/components/bootcamp/EducatorSection";
import { TrustSection } from "@/components/bootcamp/TrustSection";
import { TestimonialsWall } from "@/components/bootcamp/TestimonialsWall";
import { FAQSection } from "@/components/bootcamp/FAQSection";
import { FinalCTASection } from "@/components/bootcamp/FinalCTASection";

// Static generation — no dynamic data, no revalidation needed.
// Next.js App Router server components are statically generated by default
// when there are no dynamic APIs (cookies, headers, searchParams).
export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Middle School Math Readiness Bootcamp | MindVerse Tutor",
  description:
    "Is your child ready for Grade 6 math? Take our FREE Math Readiness Assessment and discover hidden learning gaps before middle school begins. 4 weeks, 12 live sessions, small groups.",
  keywords: [
    "middle school math readiness",
    "Grade 6 math preparation",
    "math bootcamp",
    "summer math program",
    "math tutoring online",
    "math learning gaps",
    "MindVerse Tutor",
    "math assessment free",
    "Grade 7 math",
    "fractions decimals algebra",
  ],
  openGraph: {
    title: "Middle School Math Readiness Bootcamp | MindVerse Tutor",
    description:
      "Identify and close your child's hidden math gaps before Grade 6. FREE Math Readiness Assessment. 4 weeks, 12 live sessions, expert educator, small groups.",
    type: "website",
    locale: "en_US",
    siteName: "MindVerse Tutor",
  },
  twitter: {
    card: "summary_large_image",
    title: "Middle School Math Readiness Bootcamp | MindVerse Tutor",
    description:
      "FREE Math Readiness Assessment for Grade 6 & 7 students. Identify hidden learning gaps before middle school begins.",
  },
  alternates: {
    canonical: "https://mindversetutor.com/math-bootcamp",
  },
};

export default function MathBootcampPage() {
  return (
    <div className="overflow-hidden bg-background">
      {/* S1: Hero */}
      <BootcampHero />

      {/* S2: The Problem */}
      <ProblemTimeline />

      {/* S3: Learning Gaps Roadmap */}
      <LearningGapsRoadmap />

      {/* S4: Signs of Hidden Gaps */}
      <HiddenGapsSigns />

      {/* S5: Why Summer */}
      <WhySummerSection />

      {/* S6: Assessment Showcase (most important section) */}
      <AssessmentShowcase />

      {/* S7: How It Works */}
      <HowItWorksRoadmap />

      {/* S8: Bootcamp Features */}
      <BootcampFeatures />

      {/* S9: Curriculum Timeline */}
      <CurriculumTimeline />

      {/* S10: Teaching Philosophy */}
      <TeachingPhilosophy />

      {/* S11: Before & After */}
      <BeforeAfterSection />

      {/* S12: Meet The Educator */}
      <EducatorSection />

      {/* S13: Why Parents Trust */}
      <TrustSection />

      {/* S14: Testimonials Wall */}
      <TestimonialsWall />

      {/* S15: FAQ */}
      <FAQSection />

      {/* S16: Final CTA */}
      <FinalCTASection />
    </div>
  );
}
